on:
  workflow_dispatch:
    tags:
      description: 'Enter name'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest
    - name: Apply Terraform Configuration
      run: terraform init && terraform apply -auto-approve
    - name: Enter name
      run:  |
        echo "Tags: ${{ github.event.inputs.tags }}"
    - name: sleep
      run:  sleep 50
    - name: distroy
      run:  terraform destroy -auto-approve

    
